###################################################################

# Created by write_sdc on Thu Mar 27 12:40:25 2025

###################################################################
set sdc_version 2.0

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA
set_max_fanout 4 [current_design]
set_load -pin_load 0.004 [get_ports {dout[7]}]
set_load -pin_load 0.004 [get_ports {dout[6]}]
set_load -pin_load 0.004 [get_ports {dout[5]}]
set_load -pin_load 0.004 [get_ports {dout[4]}]
set_load -pin_load 0.004 [get_ports {dout[3]}]
set_load -pin_load 0.004 [get_ports {dout[2]}]
set_load -pin_load 0.004 [get_ports {dout[1]}]
set_load -pin_load 0.004 [get_ports {dout[0]}]
set_max_capacitance 0.005 [get_ports {din[63]}]
set_max_capacitance 0.005 [get_ports {din[62]}]
set_max_capacitance 0.005 [get_ports {din[61]}]
set_max_capacitance 0.005 [get_ports {din[60]}]
set_max_capacitance 0.005 [get_ports {din[59]}]
set_max_capacitance 0.005 [get_ports {din[58]}]
set_max_capacitance 0.005 [get_ports {din[57]}]
set_max_capacitance 0.005 [get_ports {din[56]}]
set_max_capacitance 0.005 [get_ports {din[55]}]
set_max_capacitance 0.005 [get_ports {din[54]}]
set_max_capacitance 0.005 [get_ports {din[53]}]
set_max_capacitance 0.005 [get_ports {din[52]}]
set_max_capacitance 0.005 [get_ports {din[51]}]
set_max_capacitance 0.005 [get_ports {din[50]}]
set_max_capacitance 0.005 [get_ports {din[49]}]
set_max_capacitance 0.005 [get_ports {din[48]}]
set_max_capacitance 0.005 [get_ports {din[47]}]
set_max_capacitance 0.005 [get_ports {din[46]}]
set_max_capacitance 0.005 [get_ports {din[45]}]
set_max_capacitance 0.005 [get_ports {din[44]}]
set_max_capacitance 0.005 [get_ports {din[43]}]
set_max_capacitance 0.005 [get_ports {din[42]}]
set_max_capacitance 0.005 [get_ports {din[41]}]
set_max_capacitance 0.005 [get_ports {din[40]}]
set_max_capacitance 0.005 [get_ports {din[39]}]
set_max_capacitance 0.005 [get_ports {din[38]}]
set_max_capacitance 0.005 [get_ports {din[37]}]
set_max_capacitance 0.005 [get_ports {din[36]}]
set_max_capacitance 0.005 [get_ports {din[35]}]
set_max_capacitance 0.005 [get_ports {din[34]}]
set_max_capacitance 0.005 [get_ports {din[33]}]
set_max_capacitance 0.005 [get_ports {din[32]}]
set_max_capacitance 0.005 [get_ports {din[31]}]
set_max_capacitance 0.005 [get_ports {din[30]}]
set_max_capacitance 0.005 [get_ports {din[29]}]
set_max_capacitance 0.005 [get_ports {din[28]}]
set_max_capacitance 0.005 [get_ports {din[27]}]
set_max_capacitance 0.005 [get_ports {din[26]}]
set_max_capacitance 0.005 [get_ports {din[25]}]
set_max_capacitance 0.005 [get_ports {din[24]}]
set_max_capacitance 0.005 [get_ports {din[23]}]
set_max_capacitance 0.005 [get_ports {din[22]}]
set_max_capacitance 0.005 [get_ports {din[21]}]
set_max_capacitance 0.005 [get_ports {din[20]}]
set_max_capacitance 0.005 [get_ports {din[19]}]
set_max_capacitance 0.005 [get_ports {din[18]}]
set_max_capacitance 0.005 [get_ports {din[17]}]
set_max_capacitance 0.005 [get_ports {din[16]}]
set_max_capacitance 0.005 [get_ports {din[15]}]
set_max_capacitance 0.005 [get_ports {din[14]}]
set_max_capacitance 0.005 [get_ports {din[13]}]
set_max_capacitance 0.005 [get_ports {din[12]}]
set_max_capacitance 0.005 [get_ports {din[11]}]
set_max_capacitance 0.005 [get_ports {din[10]}]
set_max_capacitance 0.005 [get_ports {din[9]}]
set_max_capacitance 0.005 [get_ports {din[8]}]
set_max_capacitance 0.005 [get_ports {din[7]}]
set_max_capacitance 0.005 [get_ports {din[6]}]
set_max_capacitance 0.005 [get_ports {din[5]}]
set_max_capacitance 0.005 [get_ports {din[4]}]
set_max_capacitance 0.005 [get_ports {din[3]}]
set_max_capacitance 0.005 [get_ports {din[2]}]
set_max_capacitance 0.005 [get_ports {din[1]}]
set_max_capacitance 0.005 [get_ports {din[0]}]
set_max_capacitance 0.005 [get_ports pkt_rec]
set_max_capacitance 0.005 [get_ports en]
set_max_capacitance 0.005 [get_ports clk]
set_max_capacitance 0.005 [get_ports rst]
set_max_capacitance 0.005 [get_ports SPI_en]
set_max_fanout 4 [get_ports {din[63]}]
set_max_fanout 4 [get_ports {din[62]}]
set_max_fanout 4 [get_ports {din[61]}]
set_max_fanout 4 [get_ports {din[60]}]
set_max_fanout 4 [get_ports {din[59]}]
set_max_fanout 4 [get_ports {din[58]}]
set_max_fanout 4 [get_ports {din[57]}]
set_max_fanout 4 [get_ports {din[56]}]
set_max_fanout 4 [get_ports {din[55]}]
set_max_fanout 4 [get_ports {din[54]}]
set_max_fanout 4 [get_ports {din[53]}]
set_max_fanout 4 [get_ports {din[52]}]
set_max_fanout 4 [get_ports {din[51]}]
set_max_fanout 4 [get_ports {din[50]}]
set_max_fanout 4 [get_ports {din[49]}]
set_max_fanout 4 [get_ports {din[48]}]
set_max_fanout 4 [get_ports {din[47]}]
set_max_fanout 4 [get_ports {din[46]}]
set_max_fanout 4 [get_ports {din[45]}]
set_max_fanout 4 [get_ports {din[44]}]
set_max_fanout 4 [get_ports {din[43]}]
set_max_fanout 4 [get_ports {din[42]}]
set_max_fanout 4 [get_ports {din[41]}]
set_max_fanout 4 [get_ports {din[40]}]
set_max_fanout 4 [get_ports {din[39]}]
set_max_fanout 4 [get_ports {din[38]}]
set_max_fanout 4 [get_ports {din[37]}]
set_max_fanout 4 [get_ports {din[36]}]
set_max_fanout 4 [get_ports {din[35]}]
set_max_fanout 4 [get_ports {din[34]}]
set_max_fanout 4 [get_ports {din[33]}]
set_max_fanout 4 [get_ports {din[32]}]
set_max_fanout 4 [get_ports {din[31]}]
set_max_fanout 4 [get_ports {din[30]}]
set_max_fanout 4 [get_ports {din[29]}]
set_max_fanout 4 [get_ports {din[28]}]
set_max_fanout 4 [get_ports {din[27]}]
set_max_fanout 4 [get_ports {din[26]}]
set_max_fanout 4 [get_ports {din[25]}]
set_max_fanout 4 [get_ports {din[24]}]
set_max_fanout 4 [get_ports {din[23]}]
set_max_fanout 4 [get_ports {din[22]}]
set_max_fanout 4 [get_ports {din[21]}]
set_max_fanout 4 [get_ports {din[20]}]
set_max_fanout 4 [get_ports {din[19]}]
set_max_fanout 4 [get_ports {din[18]}]
set_max_fanout 4 [get_ports {din[17]}]
set_max_fanout 4 [get_ports {din[16]}]
set_max_fanout 4 [get_ports {din[15]}]
set_max_fanout 4 [get_ports {din[14]}]
set_max_fanout 4 [get_ports {din[13]}]
set_max_fanout 4 [get_ports {din[12]}]
set_max_fanout 4 [get_ports {din[11]}]
set_max_fanout 4 [get_ports {din[10]}]
set_max_fanout 4 [get_ports {din[9]}]
set_max_fanout 4 [get_ports {din[8]}]
set_max_fanout 4 [get_ports {din[7]}]
set_max_fanout 4 [get_ports {din[6]}]
set_max_fanout 4 [get_ports {din[5]}]
set_max_fanout 4 [get_ports {din[4]}]
set_max_fanout 4 [get_ports {din[3]}]
set_max_fanout 4 [get_ports {din[2]}]
set_max_fanout 4 [get_ports {din[1]}]
set_max_fanout 4 [get_ports {din[0]}]
set_max_fanout 4 [get_ports pkt_rec]
set_max_fanout 4 [get_ports en]
set_max_fanout 4 [get_ports clk]
set_max_fanout 4 [get_ports rst]
set_max_fanout 4 [get_ports SPI_en]
set_ideal_network [get_ports clk]
create_clock [get_ports clk]  -period 100  -waveform {0 50}
set_clock_uncertainty 0.1  [get_clocks clk]
set_clock_transition -max -rise 0.06 [get_clocks clk]
set_clock_transition -max -fall 0.06 [get_clocks clk]
set_clock_transition -min -rise 0.06 [get_clocks clk]
set_clock_transition -min -fall 0.06 [get_clocks clk]
set_input_delay -clock clk  0.02  [get_ports {din[63]}]
set_input_delay -clock clk  0.02  [get_ports {din[62]}]
set_input_delay -clock clk  0.02  [get_ports {din[61]}]
set_input_delay -clock clk  0.02  [get_ports {din[60]}]
set_input_delay -clock clk  0.02  [get_ports {din[59]}]
set_input_delay -clock clk  0.02  [get_ports {din[58]}]
set_input_delay -clock clk  0.02  [get_ports {din[57]}]
set_input_delay -clock clk  0.02  [get_ports {din[56]}]
set_input_delay -clock clk  0.02  [get_ports {din[55]}]
set_input_delay -clock clk  0.02  [get_ports {din[54]}]
set_input_delay -clock clk  0.02  [get_ports {din[53]}]
set_input_delay -clock clk  0.02  [get_ports {din[52]}]
set_input_delay -clock clk  0.02  [get_ports {din[51]}]
set_input_delay -clock clk  0.02  [get_ports {din[50]}]
set_input_delay -clock clk  0.02  [get_ports {din[49]}]
set_input_delay -clock clk  0.02  [get_ports {din[48]}]
set_input_delay -clock clk  0.02  [get_ports {din[47]}]
set_input_delay -clock clk  0.02  [get_ports {din[46]}]
set_input_delay -clock clk  0.02  [get_ports {din[45]}]
set_input_delay -clock clk  0.02  [get_ports {din[44]}]
set_input_delay -clock clk  0.02  [get_ports {din[43]}]
set_input_delay -clock clk  0.02  [get_ports {din[42]}]
set_input_delay -clock clk  0.02  [get_ports {din[41]}]
set_input_delay -clock clk  0.02  [get_ports {din[40]}]
set_input_delay -clock clk  0.02  [get_ports {din[39]}]
set_input_delay -clock clk  0.02  [get_ports {din[38]}]
set_input_delay -clock clk  0.02  [get_ports {din[37]}]
set_input_delay -clock clk  0.02  [get_ports {din[36]}]
set_input_delay -clock clk  0.02  [get_ports {din[35]}]
set_input_delay -clock clk  0.02  [get_ports {din[34]}]
set_input_delay -clock clk  0.02  [get_ports {din[33]}]
set_input_delay -clock clk  0.02  [get_ports {din[32]}]
set_input_delay -clock clk  0.02  [get_ports {din[31]}]
set_input_delay -clock clk  0.02  [get_ports {din[30]}]
set_input_delay -clock clk  0.02  [get_ports {din[29]}]
set_input_delay -clock clk  0.02  [get_ports {din[28]}]
set_input_delay -clock clk  0.02  [get_ports {din[27]}]
set_input_delay -clock clk  0.02  [get_ports {din[26]}]
set_input_delay -clock clk  0.02  [get_ports {din[25]}]
set_input_delay -clock clk  0.02  [get_ports {din[24]}]
set_input_delay -clock clk  0.02  [get_ports {din[23]}]
set_input_delay -clock clk  0.02  [get_ports {din[22]}]
set_input_delay -clock clk  0.02  [get_ports {din[21]}]
set_input_delay -clock clk  0.02  [get_ports {din[20]}]
set_input_delay -clock clk  0.02  [get_ports {din[19]}]
set_input_delay -clock clk  0.02  [get_ports {din[18]}]
set_input_delay -clock clk  0.02  [get_ports {din[17]}]
set_input_delay -clock clk  0.02  [get_ports {din[16]}]
set_input_delay -clock clk  0.02  [get_ports {din[15]}]
set_input_delay -clock clk  0.02  [get_ports {din[14]}]
set_input_delay -clock clk  0.02  [get_ports {din[13]}]
set_input_delay -clock clk  0.02  [get_ports {din[12]}]
set_input_delay -clock clk  0.02  [get_ports {din[11]}]
set_input_delay -clock clk  0.02  [get_ports {din[10]}]
set_input_delay -clock clk  0.02  [get_ports {din[9]}]
set_input_delay -clock clk  0.02  [get_ports {din[8]}]
set_input_delay -clock clk  0.02  [get_ports {din[7]}]
set_input_delay -clock clk  0.02  [get_ports {din[6]}]
set_input_delay -clock clk  0.02  [get_ports {din[5]}]
set_input_delay -clock clk  0.02  [get_ports {din[4]}]
set_input_delay -clock clk  0.02  [get_ports {din[3]}]
set_input_delay -clock clk  0.02  [get_ports {din[2]}]
set_input_delay -clock clk  0.02  [get_ports {din[1]}]
set_input_delay -clock clk  0.02  [get_ports {din[0]}]
set_input_delay -clock clk  0.02  [get_ports pkt_rec]
set_input_delay -clock clk  0.02  [get_ports en]
set_input_delay -clock clk  0.02  [get_ports rst]
set_input_delay -clock clk  0.02  [get_ports SPI_en]
set_output_delay -clock clk  0.02  [get_ports {dout[7]}]
set_output_delay -clock clk  0.02  [get_ports {dout[6]}]
set_output_delay -clock clk  0.02  [get_ports {dout[5]}]
set_output_delay -clock clk  0.02  [get_ports {dout[4]}]
set_output_delay -clock clk  0.02  [get_ports {dout[3]}]
set_output_delay -clock clk  0.02  [get_ports {dout[2]}]
set_output_delay -clock clk  0.02  [get_ports {dout[1]}]
set_output_delay -clock clk  0.02  [get_ports {dout[0]}]
