###################################################################

# Created by write_sdc on Wed Apr 9 11:14:36 2025

###################################################################
set sdc_version 2.0

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA
set_max_fanout 4 [current_design]
set_load -pin_load 0.004 [get_ports {OUT[7]}]
set_load -pin_load 0.004 [get_ports {OUT[6]}]
set_load -pin_load 0.004 [get_ports {OUT[5]}]
set_load -pin_load 0.004 [get_ports {OUT[4]}]
set_load -pin_load 0.004 [get_ports {OUT[3]}]
set_load -pin_load 0.004 [get_ports {OUT[2]}]
set_load -pin_load 0.004 [get_ports {OUT[1]}]
set_load -pin_load 0.004 [get_ports {OUT[0]}]
set_load -pin_load 0.004 [get_ports MISO]
set_max_capacitance 0.005 [get_ports rst]
set_max_capacitance 0.005 [get_ports MOSI]
set_max_capacitance 0.005 [get_ports SCK]
set_max_capacitance 0.005 [get_ports SS]
set_max_capacitance 0.005 [get_ports {DATA[7]}]
set_max_capacitance 0.005 [get_ports {DATA[6]}]
set_max_capacitance 0.005 [get_ports {DATA[5]}]
set_max_capacitance 0.005 [get_ports {DATA[4]}]
set_max_capacitance 0.005 [get_ports {DATA[3]}]
set_max_capacitance 0.005 [get_ports {DATA[2]}]
set_max_capacitance 0.005 [get_ports {DATA[1]}]
set_max_capacitance 0.005 [get_ports {DATA[0]}]
set_max_fanout 4 [get_ports rst]
set_max_fanout 4 [get_ports MOSI]
set_max_fanout 4 [get_ports SCK]
set_max_fanout 4 [get_ports SS]
set_max_fanout 4 [get_ports {DATA[7]}]
set_max_fanout 4 [get_ports {DATA[6]}]
set_max_fanout 4 [get_ports {DATA[5]}]
set_max_fanout 4 [get_ports {DATA[4]}]
set_max_fanout 4 [get_ports {DATA[3]}]
set_max_fanout 4 [get_ports {DATA[2]}]
set_max_fanout 4 [get_ports {DATA[1]}]
set_max_fanout 4 [get_ports {DATA[0]}]
set_ideal_network [get_ports SCK]
create_clock [get_ports SCK]  -period 100  -waveform {0 50}
set_clock_uncertainty 0.1  [get_clocks SCK]
set_clock_transition -max -rise 0.06 [get_clocks SCK]
set_clock_transition -max -fall 0.06 [get_clocks SCK]
set_clock_transition -min -rise 0.06 [get_clocks SCK]
set_clock_transition -min -fall 0.06 [get_clocks SCK]
set_input_delay -clock SCK  0.02  [get_ports rst]
set_input_delay -clock SCK  0.02  [get_ports MOSI]
set_input_delay -clock SCK  0.02  [get_ports SS]
set_input_delay -clock SCK  0.02  [get_ports {DATA[7]}]
set_input_delay -clock SCK  0.02  [get_ports {DATA[6]}]
set_input_delay -clock SCK  0.02  [get_ports {DATA[5]}]
set_input_delay -clock SCK  0.02  [get_ports {DATA[4]}]
set_input_delay -clock SCK  0.02  [get_ports {DATA[3]}]
set_input_delay -clock SCK  0.02  [get_ports {DATA[2]}]
set_input_delay -clock SCK  0.02  [get_ports {DATA[1]}]
set_input_delay -clock SCK  0.02  [get_ports {DATA[0]}]
set_output_delay -clock SCK  0.02  [get_ports {OUT[7]}]
set_output_delay -clock SCK  0.02  [get_ports {OUT[6]}]
set_output_delay -clock SCK  0.02  [get_ports {OUT[5]}]
set_output_delay -clock SCK  0.02  [get_ports {OUT[4]}]
set_output_delay -clock SCK  0.02  [get_ports {OUT[3]}]
set_output_delay -clock SCK  0.02  [get_ports {OUT[2]}]
set_output_delay -clock SCK  0.02  [get_ports {OUT[1]}]
set_output_delay -clock SCK  0.02  [get_ports {OUT[0]}]
set_output_delay -clock SCK  0.02  [get_ports MISO]
